# Generated by Django 5.2.5 on 2025-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('selected_rooms', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nights', models.IntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
