# Generated by Django 5.2.5 on 2025-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('number_of_guests', models.IntegerField()),
                ('reservation_time', models.CharField(max_length=10)),
                ('selected_dishes', models.JSONField(default=list)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
